axiom-crypto/halo2-lib

halo2-base/src/gates/flex_gate.rs, halo2-ecc/src/bigint/mod.rs, halo2-ecc/src/ecc/fixed_base.rs, halo2-ecc/src/ecc/mod.rs, halo2-ecc/src/ecc/pippenger.rs, halo2-ecc/src/fields/tests.rs, halo2-ecc/src/secp256k1/tests/ecdsa.rs
apply some clippy fixes via
`cargo +nightly clippy --fix -Z unstable-options --allow-dirty --allow-staged`
there still some hints that require manual changes, for examples needless lifetimes.
=> chore: clippy --fix

halo2-base/src/gates/flex_gate.rs, halo2-base/src/gates/tests/idx_to_indicator.rs, halo2-base/src/gates/tests/mod.rs
Previous implementation of `idx_to_indicator` was under-constrained. At `idx` value could be `0` or `1` when it should only be allowed to be `1`. 
Added comprehensive test coverage for this function.
=> Fix: under-constrained `idx_to_indicator`

halo2-base/src/gates/flex_gate.rs
The length of input iterator is only checked via size hint and `debug_assert_eq!`. Since this length is used to compute the advice offset of a returned cell, for safety we should use `assert_eq!`.
=> Fix: `inner_product_left_last` size hint

halo2-base/src/gates/builder.rs, halo2-base/src/gates/mod.rs, halo2-base/src/gates/range.rs, halo2-base/src/gates/tests/mod.rs, halo2-base/src/lib.rs
Make `RangeCircuitBuilder` and `RangeWithInstanceCircuitBuilder` automatically detect whether to create and load a lookup table or not (for range checks). 
This way we no longer need to decide whether to use `GateCircuitBuilder` or `RangeCircuitBuilder` (the former is kept for compatibility for now).
=> Smart range circuit builder

halo2-base/src/gates/builder.rs, halo2-base/src/gates/mod.rs, halo2-base/src/gates/range.rs, halo2-base/src/gates/tests/mod.rs, halo2-base/src/lib.rs
Make `RangeCircuitBuilder` and `RangeWithInstanceCircuitBuilder` automatically detect whether to create and load a lookup table or not (for range checks). 
This way we no longer need to decide whether to use `GateCircuitBuilder` or `RangeCircuitBuilder` (the former is kept for compatibility for now).
=> Smart Range Builder

halo2-base/src/gates/range.rs
Previously when `a_num_bits <= b_num_bits`, it was trying to range check `div_hi` to `0` bits, which resulted in a panic since `range_check` doesn't handle `0` bits case. This is now fixed.
=> fix: `div_mod_var` when `a_num_bits <= b_num_bits`

halo2-ecc/src/ecc/ecdsa.rs, halo2-ecc/src/fields/fp.rs, halo2-ecc/src/secp256k1/tests/ecdsa.rs
NOTE: current ecdsa requires `r,s` to be given as proper CRT integers
TODO: newtypes to guard this assumption
=> fix(ecdsa): allow u1*G == u2*PK case

halo2-base/src/gates/flex_gate.rs, halo2-base/src/gates/tests/flex_gate_tests.rs, halo2-base/src/gates/tests/pos_prop_tests.rs, halo2-base/src/lib.rs, halo2-base/src/utils.rs, hashes/zkevm-keccak/src/keccak_packed_multi.rs, hashes/zkevm-keccak/src/util.rs, hashes/zkevm-keccak/src/util/eth_types.rs
`ff::PrimeField::Repr` allows implementation-specific endianness. For most use cases we need to know the actual endian-ness to do conversions to integers. 
We will guard against this by only implementing our trait `ScalarField` for `FieldExt` where `Repr` is little-endian.
=> Guard `ScalarField` byte representations to always be little-endian

halo2-base/src/gates/range.rs, halo2-base/src/gates/tests/pos_prop_tests.rs, halo2-base/src/gates/tests/range_gate_tests.rs, halo2-base/src/gates/tests/test_ground_truths.rs
2 errors:
* Witness gen for last bit was wrong (used xor instead of &)
* `ctx.get` was called after `range_check` so it was getting the wrong cell
=> fix: get_last_bit two errors

halo2-base/src/gates/flex_gate.rs, halo2-base/src/gates/range.rs, halo2-base/src/utils.rs, halo2-ecc/src/bigint/add_no_carry.rs, halo2-ecc/src/bigint/big_is_equal.rs, halo2-ecc/src/bigint/big_is_zero.rs, halo2-ecc/src/bigint/carry_mod.rs, halo2-ecc/src/bigint/check_carry_mod_to_zero.rs, halo2-ecc/src/bigint/mul_no_carry.rs, halo2-ecc/src/bigint/scalar_mul_and_add_no_carry.rs, halo2-ecc/src/bigint/select.rs, halo2-ecc/src/bigint/sub.rs, halo2-ecc/src/bigint/sub_no_carry.rs, halo2-ecc/src/ecc/fixed_base.rs, halo2-ecc/src/ecc/pippenger.rs, halo2-ecc/src/fields/fp.rs, hashes/zkevm-keccak/src/util/constraint_builder.rs
Debug asserts usually used for assumptions on inputs. These assumptions are now made clearly in documentation.
Most debug asserts that could be replaced by `zip_eq` have been.
We still opt to keep debug asserts instead of asserts (provided there is proper documentation), since most functions in halo2-ecc are fairly low-level and performance critical.
=> Add documentation for all debug_asserts

halo2-ecc/src/bn254/final_exp.rs, halo2-ecc/src/ecc/ecdsa.rs, halo2-ecc/src/ecc/mod.rs, halo2-ecc/src/fields/fp.rs, halo2-ecc/src/fields/mod.rs
`divide, neg_divide` renamed `divide_unsafe, neg_divide_unsafe` because they do not check denominator is nonzero.
Added `divide` and `neg_divide` functions where denominator is checked to be nonzero. 
We continue using `divide_unsafe` in internal halo2-ecc functions, but add documentation about function input assumptions that justify this usage.
=> fix: `FieldChip::divide` renamed `divide_unsafe`

halo2-ecc/src/ecc/ecdsa.rs, halo2-ecc/src/ecc/mod.rs, halo2-ecc/src/ecc/pippenger.rs
* `msm` implementations now always use `ec_{add,sub}_unequal` in strict mode for safety
* Add docs to `scalar_multiply` and a flag to specify when it's safe to turn off some strict assumptions
=> feat: use strict ec ops more often

halo2-base/Cargo.toml, halo2-base/src/gates/builder.rs, halo2-base/src/gates/builder/parallelize.rs, halo2-ecc/src/ecc/fixed_base.rs, halo2-ecc/src/ecc/mod.rs, halo2-ecc/src/ecc/pippenger.rs
Multi-threading of witness generation is tricky because one has to ensure the circuit column assignment order stays deterministic. To ensure good developer experience / avoiding pitfalls, we provide a new helper function for this.
=> feat: add `parallelize_in` helper function

halo2-ecc/src/bn254/tests/fixed_base_msm.rs, halo2-ecc/src/ecc/ecdsa.rs, halo2-ecc/src/ecc/fixed_base.rs, halo2-ecc/src/ecc/mod.rs
We still require fixed base points to be non-identity, but now handle the case when scalars may be zero or the final MSM value is identity point.
=> feat: `fixed_base::msm_par` handles identity point

halo2-base/src/gates/tests/pos_prop_tests.rs, halo2-base/src/gates/tests/range_gate_tests.rs
This test doesn't run any prover so the input must satisfy range check assumption. More serious coverage is provided by
`prop_test_neg_is_less_than_safe`
=> fix: `prop_test_is_less_than_safe`

halo2-base/Cargo.toml, halo2-base/src/utils.rs
for easier integration with external crates, blanket implement `ScalarField` for `FieldExt + Hash` of fields that are ~256 bits
We do this in community-edition but not main branch because `ScalarField` assumes that `F::Repr` is in little endian. `ff::Field` leaves `Repr` endian-ness to be implementation specific, so this is not entirely safe
=> feat: revert to blanket implementation of `ScalarField`

halo2-base/src/gates/flex_gate.rs, halo2-base/src/gates/tests/bitwise_rotate.rs, halo2-base/src/gates/tests/general.rs, halo2-base/src/gates/tests/idx_to_indicator.rs, halo2-base/src/gates/tests/mod.rs, halo2-base/src/lib.rs
- Add `const_right_rotate_unsafe` and `const_left_rotate_unsafe` into `GateInstructions`. 
- These functions can bitwise left/rotate rotate a unsigned integer by a const bit.
- These functions don't do range checking so it's unsafe.
=> [feat] Add bitwise rotate operators for const bits

halo2-ecc/src/bn254/pairing.rs, halo2-ecc/src/bn254/tests/pairing.rs
> Note: reopened from https://github.com/axiom-crypto/halo2-lib/pull/64
Added `pairing_check()` to `PairingChip`. Conducts an efficient check e(P, Q) = e(S, T) using only one final exponentiation. Constrains (e'(-P, Q)e'(S, T))^x = 1, where e' is the optimal ate pairing without the final exponentiation. Reduces number of necessary advice cells by ~30%.
Two unit tests, one where the pairing check should pass and one where it should fail.
=> Efficient pairing check for PairingChip

halo2-base/src/gates/tests/general.rs, halo2-base/src/utils.rs
For community contributions it's better to have a blanket trait implementation, even if slightly less optimized. Otherwise Rust prevents you from implementing a trait you don't own for a struct you don't own.
Since field structs are usually implemented in halo2curves, it doesn't make sense for them to implement additional halo2-lib traits.
=> feat: `BigPrimeField = ScalarField = FieldExt + Hash`

.github/workflows/ci.yml, halo2-ecc/configs/bn254/bench_fixed_msm.t.config, halo2-ecc/configs/bn254/bench_msm.t.config, halo2-ecc/configs/bn254/bench_pairing.t.config, halo2-ecc/src/bn254/tests/fixed_base_msm.rs, halo2-ecc/src/bn254/tests/mod.rs, halo2-ecc/src/bn254/tests/msm_sum_infinity.rs, halo2-ecc/src/bn254/tests/msm_sum_infinity_fixed_base.rs, halo2-ecc/src/ecc/ecdsa.rs, halo2-ecc/src/ecc/fixed_base.rs, halo2-ecc/src/ecc/mod.rs, halo2-ecc/src/secp256k1/tests/ecdsa_tests.rs, halo2-ecc/src/secp256k1/tests/mod.rs
* Add tests for MSM where output is identity point
* Previously when true output is identity in MSM, Rust will panic because we invoke `divide_unsafe` with `nonzero / zero`. We have fixed this in `ec_sub_strict` now.
* Previously fixed base scalar multiply would panic when computing `[-1]P` because even though the circuit constraints were correct, it needed to compute `[-1]P + P` for witness generation and this had division by zero issues. This is now fixed by using a generic accumulator point.
* Made similar changes to variable base `scalar_multiply` to handle edge cases and identity point better.
=> [Fix] Panic when dealing with identity point

halo2-ecc/src/ecc/mod.rs
It is possible in `scalar_multiply` that if `2^window_bits * ceil(scalar / 2^window_bits)` is greater than order of `P` (minus epsilon), there is an overconstraint preventing completeness.
For now we replace `scalar_multiply` with a passthrough to `multi_scalar_multiply`, which does not have this issue.
=> [Fix] scalar multiply completeness

halo2-base/src/gates/range.rs, halo2-base/src/gates/tests/range_gate.rs, halo2-ecc/src/fields/fp.rs, halo2-ecc/src/fields/tests/fp/mod.rs
Previously the range check in `FpChip` was quite specialized to range checking a BigInt in base `2^n` with `k` limbs had at most `max_bits` bits, where `max_bits >= n * (k - 1)`.
In practice we only cared about the case where `max_bits = 254, n = 88, k = 3` so this was ok. For future support for other fields (e.g., those for BLS12-381, this assumption is a blocker).
The change is both easy and small in diff.
=> feat: `FpChip::range_check` now works with `max_bits < n * (k-1)`

hashes/zkevm-keccak/src/keccak_packed_multi/tests.rs
Currently with `first_pass = true`, it skips the first pass, but when
feature "halo2-axiom" is used, there is only one pass of `synthesize` so
the whole thing gets skipped. Mea culpa!
=> fix(test): zkevm-keccak test should have `first_pass = SKIP_FIRST_PASS`

halo2-base/src/lib.rs
Functions only available for testing:
* `ctx.debug_assert_false` for debug break point to search for other constrain failures in mock prover
* `assigned_value.debug_prank(prank_value)` to prank witness values for negative tests
=> feat: add debugging functions

.github/workflows/ci.yml, hashes/poseidon/src/lib.rs, hashes/poseidon/src/tests.rs
Closes #95 
This sponge is not compatible with other existing native Poseidon sponges - by native I mean executed directly as Rust code, rather than inside a Halo 2 circuit. Specifically, our native reference is [https://github.com/scroll-tech/poseidon/](https://github.com/scroll-tech/poseidon/).
The issue boils down to [line 54](https://github.com/axiom-crypto/halo2-lib/blob/community-edition/hashes/poseidon/src/lib.rs#L54) of the function `absorb_with_pre_constants`. Judging by other implementations, the input should not be added to the first element of the state (which I interpret as the capacity). Furthermore, the current code skips pre-constant addition to the capacity if the input is empty, which should not be the case.
Replacing the cited line by one which just adds the …
=> Compatibility with native Poseidon sponge

halo2-base/src/gates/flex_gate.rs, halo2-base/src/gates/tests/flex_gate.rs, halo2-base/src/gates/tests/pos_prop.rs, hashes/zkevm-keccak/src/keccak_packed_multi/tests.rs
Uses standard square and multiply method.
=> feat(halo2-base): add `GateChip::pow_var`

halo2-base/src/gates/flex_gate.rs, halo2-base/src/gates/tests/flex_gate.rs, halo2-base/src/gates/tests/pos_prop.rs, halo2-base/src/gates/tests/utils.rs
I was in need of this, though I'm not sure whether this is common enough of an operation to have an explicit convenience function.
This can of course be achieved in two steps by first negation with `gate.neg()` and then `gate.mul_add()` but it adds extra constraints.
=> Add `sub_mul` to GateInstructions

halo2-base/Cargo.toml, halo2-base/src/lib.rs, halo2-base/src/poseidon/mds.rs, halo2-base/src/poseidon/mod.rs, halo2-base/src/poseidon/spec.rs, halo2-base/src/poseidon/state.rs, halo2-base/src/poseidon/tests.rs, halo2-base/src/poseidon/tests/compatibility.rs, halo2-base/src/poseidon/tests/mod.rs, halo2-base/src/utils/mod.rs
- The implementation is from [community edition](https://github.com/axiom-crypto/halo2-lib/blob/f2eacb1f7fdbb760213cf8037a1bd1a10672133f/hashes/poseidon/src/lib.rs) but using [OptimizedPoseidonSpec](https://github.com/axiom-crypto/snark-verifier/blob/43e95ce63a65e9de5843a6e0b994b3b3e7da618c/snark-verifier/src/util/hash/poseidon.rs#L60).
- The chip is stateful.
- [Side effect] `ScalarField` is `Ord` instead of `PartialOrd` + `PartialEq`.
=> [Feat] Add Poseidon Hasher Chip

halo2-base/Cargo.toml, halo2-base/benches/inner_product.rs, halo2-base/benches/mul.rs, halo2-base/examples/inner_product.rs, halo2-base/src/gates/tests/flex_gate.rs, halo2-base/src/utils/testing.rs, halo2-ecc/benches/fixed_base_msm.rs, halo2-ecc/benches/fp_mul.rs, halo2-ecc/benches/msm.rs, halo2-ecc/src/bn254/tests/fixed_base_msm.rs, halo2-ecc/src/bn254/tests/msm.rs, halo2-ecc/src/bn254/tests/pairing.rs, halo2-ecc/src/secp256k1/tests/ecdsa.rs
- Reduce code bloat in benchmarks by using `gen_proof` and `check_proof` helper functions
- Add initial version of `bench_builder` helper function. Future benches should use this to save even more code.
=> cleanup: use test-utils for benching

halo2-base/Cargo.toml, halo2-base/src/gates/flex_gate.rs, halo2-base/src/gates/tests/flex_gate.rs, halo2-base/src/poseidon/hasher/mod.rs, halo2-base/src/poseidon/hasher/state.rs, halo2-base/src/poseidon/hasher/tests/compatibility.rs, halo2-base/src/poseidon/hasher/tests/hasher.rs, halo2-base/src/poseidon/hasher/tests/mod.rs, halo2-base/src/poseidon/hasher/tests/state.rs, halo2-base/src/poseidon/mod.rs
- Rename `PoseidonHasher` to `PoseidonSponge`.
- Move `permutation` from `poseidon/hasher/mod.rs` to `poseidon/hasher/state.rs`
- Add new `PoseidonHasher` which can stateless hash arrays.
- Add some utility functions into `GateChip`.
Unit testing
=> [feat] Add Poseidon Chip

hashes/zkevm/Cargo.toml, hashes/zkevm/src/keccak/keccak_packed_multi.rs, hashes/zkevm/src/keccak/mod.rs, hashes/zkevm/src/keccak/tests.rs, hashes/zkevm/src/util/constraint_builder.rs, hashes/zkevm/src/util/expression.rs, hashes/zkevm/src/util/mod.rs, hashes/zkevm/src/util/word.rs
- Expose raw keccak results instead of RLCs.
- Import `word.rs` from [PSE zkevm circuits](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/96b3c4e7a9104413a0a4c22efea6162b9940f0c0/zkevm-circuits/src/util/word.rs).
=> [feat] Keccak Raw Output

halo2-base/Cargo.toml, hashes/zkevm/src/keccak/keccak_packed_multi.rs, hashes/zkevm/src/keccak/mod.rs, hashes/zkevm/src/util/expression.rs
Now that halo2-base has `raw_assign_{advice,fixed}`, use those instead of `assign_advice_custom`.
I kept `KeccakAssignedValue` as type alias of `Halo2AssignedCell` just to reduce code changes.
=> Use `raw_assign_{advice,fixed}` in keccak

halo2-base/src/gates/flex_gate/mod.rs, halo2-base/src/gates/flex_gate/threads/mod.rs, halo2-base/src/gates/flex_gate/threads/single_phase.rs
`single_phase::assign_with_constraints` can be made generic for any single-column "vertical" gate that uses `ROTATIONS` continguous rows. Currently our calculation of break points assumes that you only "overlap" the gates on the last cell of each rotation window.
This lets us share the `assign_with_constraints` code between `FlexGateConfig` and `RlcConfig` (in axiom-eth)
=> Generic vertical gate assignment

halo2-base/src/gates/circuit/builder.rs, halo2-base/src/gates/circuit/mod.rs, halo2-base/src/gates/flex_gate/threads/multi_phase.rs, halo2-base/src/gates/flex_gate/threads/single_phase.rs
We sometimes want to clone `BaseCircuitBuilder` completely (for example
to re-run witness generation). The derived clone only clones the shared
references, instead of the underlying objects.
=> Add `deep_clone` to `BaseCircuitBuilder`

halo2-base/src/poseidon/hasher/mds.rs, halo2-base/src/poseidon/hasher/spec.rs
For compatibility with `snark-verifier`
=> chore: use `PrimeField` for `OptimizedPoseidonSpec`

halo2-base/src/poseidon/hasher/mds.rs, halo2-base/src/poseidon/hasher/spec.rs
=> chore: add getter functions to Poseidon spec

halo2-base/src/gates/range/mod.rs, halo2-base/src/lib.rs, halo2-base/src/virtual_region/lookups.rs, halo2-base/src/virtual_region/tests/lookups/memory.rs
I was a little worried `context.id()` would not be unique when using multiple phases or managers. Adding `TypeId` should make everything unique.
=> feat: use `(TypeId, usize)` instead of `usize` for lookup tag

halo2-base/src/poseidon/hasher/mod.rs, halo2-base/src/poseidon/hasher/tests/hasher.rs, halo2-base/src/safe_types/bytes.rs, halo2-base/src/safe_types/mod.rs, halo2-base/src/safe_types/tests/bytes.rs, hashes/zkevm/src/keccak/coprocessor/circuit/leaf.rs, hashes/zkevm/src/keccak/coprocessor/encode.rs, hashes/zkevm/src/keccak/coprocessor/tests/encode.rs, hashes/zkevm/src/keccak/coprocessor/tests/mod.rs, hashes/zkevm/src/keccak/vanilla/mod.rs
- Encoding for `VarLenBytesVec` and `FixLenBytesVec`.
=> [feat] App Circuit Utils for Keccak Coprocessor

Cargo.toml, hashes/zkevm/Cargo.toml, hashes/zkevm/src/keccak/coprocessor/encode.rs, hashes/zkevm/src/keccak/coprocessor/output.rs
Currently only used for testing
=> chore(keccak): use `snark-verifier` native Poseidon for encoding

halo2-ecc/src/bn254/tests/mod.rs, halo2-ecc/src/secp256k1/tests/mod.rs, halo2-ecc/src/secp256k1/tests/schnorr_signature.rs, halo2-ecc/src/secp256k1/tests/schnorr_signature_tests.rs
solves #156 
known issues:
randomized test runs very long time tho..
=> Fix schnorr test

halo2-base/src/lib.rs, halo2-ecc/src/fields/mod.rs, halo2-ecc/src/fields/native_fp.rs, halo2-ecc/src/grumpkin/mod.rs, halo2-ecc/src/grumpkin/tests/mod.rs, halo2-ecc/src/lib.rs
same change as https://github.com/axiom-crypto/halo2-lib/pull/136/files, created a new one to base the change on community edition
=> add native field chip using native arithmetic operations & grumpkin curve chip

halo2-base/src/safe_types/mod.rs, halo2-base/src/safe_types/primitives.rs
Had to keep writing `*byte.as_ref()` because even though `SafeByte` implements `Into` for `AssignedValue`, it did not auto convert further to `QuantumCell::Existing`. 
Added that conversion to the macro. Also implement `Deref` for `SafeByte` to `AssignedValue`.
Same for `SafeBool`.
Future thought: Not sure if we should just auto-implement conversion of `T: Into<AssignedValue<F>>` into `QuantumCell::Existing`.
=> [chore] add conversion `SafePrimitive` to `QuantumCell::Existing`

hashes/zkevm/src/keccak/component/ingestion.rs
`format_requests_for_ingestion` previously only returned true capacity on error.
But it's always useful to know the true capacity and it doesn't change any codepaths.
=> chore(keccak): `format_requests` always returns true capacity

hashes/zkevm/src/keccak/component/circuit/shard.rs
For example, it's useful to access `BaseCircuitBuilder` to read public instances.
=> chore: add getters to `KeccakComponentShardCircuit`

hashes/zkevm/src/keccak/component/circuit/shard.rs
Add getters for:
- `inputs` (necessary to compute public instances)
- `hasher` (in case we want to re-use Poseidon spec)
- `gate_chip` (stateless, so harmless to provide)
=> [chore] Add getters to `KeccakComponentShardCircuit`

hashes/zkevm/src/keccak/component/encode.rs
Expose Keccak packing before Poseidon.
=> [chore] Expose Keccak Packing

halo2-base/src/poseidon/hasher/mod.rs
Add getter for `spec` in `PoseidonHasher` to avoid re-creating spec later.
=> [chore] expose `spec` in `PoseidonHasher`

halo2-base/src/virtual_region/lookups/basic.rs
`halo2-pse` `assign_region` takes a `Fn` closure not `FnOnce` because of some layouter stuff. So we have to clone `rows`.
=> [chore] fix halo2-pse build error

hashes/zkevm/src/sha256/vanilla/constraints.rs
`d_64` and `h_64` are renamed to `d_68` and `h_68` to avoid confusion. The reason is that the offset includes 4 Start rows (`NUM_START_ROWS`) which aren't mentioned in the immediate code vicinity.
=> [feat] rename `d_64, h_64` to `d_68, h_68`

hashes/zkevm/src/sha256/vanilla/constraints.rs
Avoid calling `meta.query_*` multiple times on `is_paddings` when you can do it once and then `clone`.
=> [feat] avoid double `meta.query` to same cells

hashes/zkevm/src/sha256/vanilla/constraints.rs, hashes/zkevm/src/sha256/vanilla/witness.rs
For extra security, we constrain every unused cell in the circuit explicitly to be zero. This also serves as a nice exposition of all the unused cells in the circuit.
Performance comparison on my M2Max:
Without the gate introduced in this PR:
```
Proving time for 14562 SHA256 blocks: 89.213413292s
test sha256::vanilla::tests::bit_sha256_prover::k_20 ... ok
```
With the gate introduced:
```
Proving time for 14562 SHA256 blocks: 91.113416291s
test sha256::vanilla::tests::bit_sha256_prover::k_20 ... ok
```
This is a 2% increase in proving time. It seems acceptable to incur this performance hit for the additional security guarantees.
=> feat: constrain all unused cells to be zero

hashes/zkevm/src/sha256/vanilla/columns.rs, hashes/zkevm/src/sha256/vanilla/constraints.rs, hashes/zkevm/src/sha256/vanilla/witness.rs
Removed `3` columns.
Before this PR:
```
Proving time for 14562 SHA256 blocks: 91.113416291s
test sha256::vanilla::tests::bit_sha256_prover::k_20 ... ok
```
Now:
```
test sha256::vanilla::tests::bit_sha256_prover::k_20 has been running for over 60 seconds
Proving time for 14562 SHA256 blocks: 90.144247833s
```
Doesn't seem to have made a big difference, but the changes were easy and did not affect much code.
=> [feat] reduce num columns

halo2-base/src/poseidon/hasher/mod.rs, halo2-base/src/poseidon/hasher/tests/hasher.rs, hashes/zkevm/src/keccak/component/circuit/shard.rs, hashes/zkevm/src/keccak/component/encode.rs
=> [chore] fix deref after using CopyGetters

halo2-base/Cargo.toml, hashes/zkevm/Cargo.toml, hashes/zkevm/src/keccak/component/circuit/shard.rs, hashes/zkevm/src/keccak/component/encode.rs, hashes/zkevm/src/keccak/component/output.rs, hashes/zkevm/src/keccak/vanilla/mod.rs
This is so `KeccakComponentShardCircuit` can be aggregated by `snark-verifier-sdk`. It must be done in this crate to avoid Rust's orphan rule.
=> [feat] implement `CircuitExt` for `KeccakComponentShardCircuit`

hashes/zkevm/src/sha256/vanilla/columns.rs, hashes/zkevm/src/sha256/vanilla/constraints.rs, hashes/zkevm/src/sha256/vanilla/witness.rs
since it is part of the overall input recovery data
=> chore: move `is_final` to `ShaTable`

.github/workflows/ci.yml, halo2-base/Cargo.toml, halo2-base/src/gates/tests/general.rs, halo2-ecc/Cargo.toml, halo2-ecc/src/fields/tests/fp/mod.rs
Only works for `halo2-pse` because the feature is currently disabled for `halo2-axiom`.
Test using
```
cargo t plot_gates --no-default-features --features "halo2-pse, dev-graph"
cargo t plot_fp --no-default-features --features "halo2-pse, dev-graph"
```
=> [chore] fix dev graph tests

halo2-base/src/utils/halo2.rs, halo2-base/src/virtual_region/copy_constraints.rs, halo2-base/src/virtual_region/lookups.rs, halo2-base/src/virtual_region/lookups/basic.rs, halo2-base/src/virtual_region/tests/lookups/memory.rs
This fixes a soundness bug described in https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/866 
Previously `BasicDynLookupConfig` allowed the `table` to be pure advice columns. As the above issue describes, this should essentially never be allowed, because each advice column has poisoned rows that the prover could put whatever they want in. This means the prover could put erroneous information in the poisoned rows to allow certain lookups to pass even when it does not contain the intended information in the `table`.
We fix this by adding a fixed column `table_is_enabled` to `BasicDynLookupConfig` and also a fixed column `key_is_enabled` for each set of `KEY_COLS` advice columns to be looked up. The`table_is_enabled` value in the fixed column defaults to 0, and we set it …
=> [fix] `BasicDynLookupConfig` needs selector on advice table to prevent lookup poison

halo2-base/README.md, halo2-base/src/gates/flex_gate/threads/single_phase.rs, halo2-base/src/lib.rs, halo2-base/src/virtual_region/copy_constraints.rs
We were using `TypeId` inside `ContextTag`, inside of `ContextCell` as a unique identifier for the virtual region the `ContextCell` belonged to. 
However, we were using the ordering of the different `TypeId`s to order the contexts, which in particular affects the order that `cells_to_lookup` is assigned to the Plonkish matrix: 
https://github.com/axiom-crypto/halo2-lib/blob/67e3a0eee37c3b25b393cdea7514fef4e8af0bf9/halo2-base/src/virtual_region/lookups.rs#L44C36-L44C36
(we order by converting `BTreeMap` to iterator).
Rust creates the values for `TypeId` in some way that varies across builds, and even when dependencies or features enabled changes. This means that the circuits created were sound, but the proving & verifying key generated for a circuit would change depending on what features …
=> fix: `TypeId` in `ContextTag` not stable across builds

halo2-base/Cargo.toml
This [PR](https://github.com/axiom-crypto/halo2/pull/26) seems to be a breaking change for halo2-lib. 
I believe this change needs to also be reflected on the `develop` branch too.
=> Change package name from `halo2_proofs` to `halo2-axiom`

halo2-base/src/gates/range/mod.rs, halo2-base/src/gates/tests/range.rs
A common operation is to decompose a number (especially a BigUint) into smaller limbs (synonyms: digits, registers). For example BigUint into `u64` limbs, BigUint into bytes, etc.
This is how `range_check` internally works, but we never exposed a general API function for it, so here it is.
=> [feat] add `decompose_le` to `RangeInstructions`

halo2-base/src/gates/flex_gate/mod.rs, halo2-base/src/gates/range/mod.rs, halo2-base/src/gates/tests/flex_gate.rs, halo2-base/src/gates/tests/range.rs
Adds a couple of functions to reconstruct field elements from their bit/limb representations
- `bits_to_num` to `GateInstructions`
- `limbs_to_num` to `RangeInstructions`
Assumes the bit/limb representation is valid and doesn't range check the bits/limbs.
One thing to note is that there can be multiple bit/limb representations that map to the same field element. For eg. with 254 bits and working on BN254, both the bit representations of `x` and `x + p` (254 bits) will map to `x`. It might make sense to range check the input to be less than `p` in such a case
=> [feat] add `bits_to_num` and `limbs_to_num`

halo2-base/src/utils/halo2.rs, halo2-base/src/virtual_region/tests/lookups/memory.rs
- Add  `CircuitWithDefault` trait which can return a circuit instance with default inputs for given params.
=> [feat] Trait for Circuit with Default Inputs

halo2-base/src/gates/flex_gate/threads/single_phase.rs, halo2-base/src/utils/halo2.rs, halo2-base/src/virtual_region/copy_constraints.rs, halo2-base/src/virtual_region/lookups.rs, halo2-base/src/virtual_region/lookups/basic.rs, halo2-base/src/virtual_region/tests/lookups/memory.rs
The problem is that in `assign_virtual_table_to_raw` it was using `assign_virtual_to_raw`, which has the following danger:
* It will "assign" a virtual cell to a raw Halo2 cell by inserting the assignment into the `HashMap` of `assigned_advices`. However later the `BaseCircuitBuilder` `raw_assign` might overwrite this assignment **without** adding any real equality constraints. Therefore the first raw cell becomes a dangling unconstrained cell.
The fix is that now `assign_virtual_table_to_raw` uses `constrain_virtual_equals_external`, and we have modified `constrain_virtual_equals_external` so that it checks whether the virtual cell has already been assigned or not. It is **only** allowed to not have been assigned if the `type_id` of the virtual cell was marked as `EXTERNAL_CELL_TYPE_ID`. …
=> [fix] soundness bug in `BasicDynLookupConfig::assign_virtual_table_to_raw`

hashes/zkevm/src/keccak/component/encode.rs
in this context, I think use  **multipiler** is more consistent
=> fix:multipiler->multipiler

hashes/zkevm/src/keccak/component/circuit/shard.rs
Some downstream traits only borrow and not mutably borrow, but we want to be able to initialize the circuit first and then set the input later.
Also added a getter for `base_circuit_builder`.
=> [chore] make `KeccakComponentShardCircuit` `inputs` into `RefCell`

hashes/zkevm/src/keccak/component/circuit/shard.rs
Used capacity is allowed to be `= params.capacity`
=> chore: fix keccak capacity check

halo2-base/Cargo.toml, halo2-base/src/utils/halo2.rs, halo2-ecc/Cargo.toml
Adds `KeygenCircuitIntent` trait to be implemented on a minimum circuit configuration struct to produce a dummy circuit that can be used for `keygen_vk, keygen_pk` to get the proving key corresponding to that configuration.
=> chore: add utility traits to aid in proving key generation

hashes/zkevm/Cargo.toml, hashes/zkevm/src/keccak/component/circuit/shard.rs, hashes/zkevm/src/keccak/component/encode.rs, hashes/zkevm/src/keccak/component/mod.rs, hashes/zkevm/src/keccak/component/output.rs
- Cache Poseidon spec
- Cache dummy circuit output
- Multiple threads in `multi_inputs_to_circuit_outputs`
=> [chore] Keccak Output Computation Optimization

halo2-base/Cargo.toml, halo2-ecc/Cargo.toml
Did not enable for zkevm-hashes because snark-verifier currently does not work with halo2-pse
=> chore: re-enable halo2-pse feature

hashes/zkevm/Cargo.toml
There is an unfortunate circular dependency where snark-verifier depends on a tag of halo2-base but then zkevm-hashes needs a tag of snark-verifier.
I will re-tag `v0.4.1-git` after merging this.
=> chore(zkevm-hashes): use git tag for snark-verifier-sdk

halo2-base/Cargo.toml, halo2-ecc/Cargo.toml, halo2-ecc/src/bn254/tests/ec_add.rs, halo2-ecc/src/ecc/ecdsa.rs, halo2-ecc/src/ecc/mod.rs
Wrote a safe version of sum that allows summands to be points at infinity and allows output to be point at infinity
=> feat: safe ecc_sum and tests

halo2-base/src/poseidon/hasher/mod.rs, halo2-base/src/safe_types/tests/bytes.rs, halo2-base/src/utils/mod.rs, halo2-ecc/src/ecc/fixed_base.rs, halo2-ecc/src/ecc/mod.rs
use [typos](https://github.com/crate-ci/typos) check all possible typos
=> chore(all):fix typos

halo2-base/src/gates/circuit/builder.rs, halo2-base/src/utils/halo2.rs, halo2-base/src/utils/mod.rs
- add `get_lower_128` with impl to `ScalarField` trait
=> add util and fix warning when compiling with halo2-pse feature mode

README.md, hashes/zkevm/src/keccak/README.md, hashes/zkevm/src/keccak/vanilla/mod.rs, hashes/zkevm/src/sha256/README.md
Hello
I found and fixed several minor typos.
Br, Elias.
=> chore: fix typo

hashes/zkevm/src/keccak/README.md
**Reason: "Process" should be in plural form in the context of describing the algorithm, as it refers to multiple steps or operations.**
**Reason: "Splitted" is an incorrect form of the verb "split". The correct past tense and past participle form is "split".**
**Reason: The verb "are" was missing, which is necessary for proper sentence structure.**
**Reason: There was a typo in the name of the algorithm. The correct spelling is "keccak_f", as used in the original SHA-3/Keccak terminology.**
=> Documentation Clarity and Consistency Updates

README.md
Hi! I noticed that some of the links in the `README.md` file were broken, so I updated them to point to the correct resources. Now all links should lead to the appropriate pages, improving navigation and documentation usability.
=> fix: update broken links docs README.md

README.md, docs/src/halo2_base/gates/builder.rs.html, docs/src/halo2_base/safe_types/mod.rs.html, docs/src/halo2_base/utils.rs.html, halo2-ecc/src/bigint/carry_mod.rs
Hi! This pull request focuses on fixing typos and addressing a broken link in the project's documentation and code comments. These changes aim to enhance clarity and accuracy while maintaining the functionality of the codebase.
- **Removed a broken link** in `README.md` related to `polymon_gan`.
- **Fixed typos** in the following files:
- `carry_mod.rs`: Corrected "forseeable" to "foreseeable".
- `builder.rs.html`: Addressed spelling errors in comments ("asignments" to "assignments", "numeber" to "number").
- `mod.rs.html`: Fixed typos such as "mulitple" to "multiple" and "varaible" to "variable".
- `utils.rs.html`: Corrected "overriden" to "overridden".
=> docs: fix typos and update broken link in documentation

halo2-base/README.md
Hi! I fixed a broken link in the `README.md`. Updated the `Assigned` module link to the correct location.
=> fix: broken link README.md

hashes/zkevm/src/sha256/README.md
I noticed a grammar issue: "version" is singular, so it requires "represents" instead of "represent."
Fixed it to make the sentence grammatically correct.
=> docs: fix grammar mistake in version representation

halo2-base/benches/inner_product.rs
Replaced the outdated and broken link to the criterion flamegraph article (previously on jibbow.com) with the current, working Medium URL by the same author. This ensures that readers can access the referenced guide for integrating flamegraphs with Criterion benchmarks. No other code changes were made.
=> Update broken flamegraph article link to current Medium URL
